services:
  frontend:
    image: frontend
    container_name: transport_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: laravel-api
    pull_policy: never
    container_name: transport_backend
    ports: 
      - "8000:80"
    volumes:
      - ./backend:/var/www
    depends_on: 
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pg_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
  
  db:
    image: postgres:latest
    container_name: transport_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"
    volumes:
      - ./bd_dados:/var/lib/postgresql